### ISSUE TITLE
Remote control

### ISSUE THREAD

**Issue by maartenberg** [svsticky/hapPi#3]
We should be able to manage the Pi remotely, to be able to respond quicker if there's some problem and nobody's in the room.

We could either set up a SSH tunnel, and/or add a bot like Hubot to the Slack channel to for instance force take control of the screen (this is a CEC command, I think some tools exist), force refresh, reboot, etc.

**Comment by tomwassenberg** [comment]
Or ask the uni (worth a try) to just open up a TCP port on our network outlet/router MAC?

**Comment by maartenberg** [comment]
We unfortunately can't, I've tried asking this for the software project.
All non-server rooms are apparently in a separate VLAN, which they
can't/won't make firewall exceptions in (this was for HFG, but I've been
told it's the same for the BBG).

**Comment by tomwassenberg** [comment]
@maartenberg This is done now right, with the SSH setup (and the buttons on the Checkout PC)?
