### ISSUE TITLE
Check reliability of Pi

### ISSUE THREAD

**Issue by maartenberg** [svsticky/hapPi#7]
We had some issues at the end of the previous year with the TV not starting at the correct time or not switching back to the Pi's output when requested. This is annoying.

We are going to check whether the TV is actually behaving properly now. Board members will report to @Riscky when the TV isn't working and needs to be restarted etc., if this happens too often we could decide to switch the signal to come from the Checkout PC or to use https://dashkiosk.readthedocs.io/en/latest/, which would then use the already connected Chromecast to show RADIO instead.

**Comment by Riscky** [comment]
It has been monitored, and seems to do alright
